version: '3.4'

services:
   # The Redis Service, this label is required for the "Links" and Connection string
  myapp_console:
    ## Get the image to use and set the container name
    image: myapp_console:latest
    container_name: myapp_console

    # State a dependancy on Redis working
    depends_on:
      - "redis_cache"

    # Location of the Dockerfile
    build:
      # context: ./MyRedis
      context: .
      dockerfile: Dockerfile

    # Set access ports for localhost on the left
    #ports:
    #  - "80:5000"
    #  - "443:5001"

    # Configure a link to Redis
    links:
      - "redis_cache"

    # The Application needs a connection string for Redis, this just needs to be the Redis Service name as defined below
    # Pass it in as an Environmental Variable
    environment:
      - Cache:Redis=redis_cache

  # The Redis Service, this label is required for the "Links" and Connection string
  redis_cache:
    # Pull the image from Docker Hub
    image: redis:latest

    # Give the container a name (any name you want)
    container_name: redis.cache